title: "Aybike Alkan"
description: "Data Science • Applied ML • Research"
url: "https://aybik.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"  # other options exist, default is fine

author:
  name: "Aybike Alkan"
  location: "Berlin"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/aybik"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/aybikealkn"

defaults:
  - scope:
      path: ""
    values:
      layout: single
